### ISSUE TITLE
Implement BFS algorithm

### ISSUE THREAD

**Issue by jcoady9** [sbonner1/Senior-Design-I#21]
Implement the BFS algorithm or another kind of algorithm that will create an order in which to visit each vertex.

**Comment by J-Fid** [comment]
Upon further review, it seems like the DFS algorithm is the best choice to use.

**Comment by shamor** [comment]
Waiting on Vertex classes to be complete before DFS can be completed

**Comment by shamor** [comment]
DFS is completed to and works well in test conditions.
