### ISSUE TITLE
Send required vertices to Arduino

### ISSUE THREAD

**Issue by sbonner1** [sbonner1/Senior-Design-I#30]
Josh will have to send an array of vertices for the drawing to the robot's board.

**Comment by J-Fid** [comment]
http://sglez.org/2008/08/05/interfacing-arduino-with-c-and-libserial/

//Serial communication with the Arduino IDE.

**Comment by shamor** [comment]
Vertices can also be sent by writing to the devise file: Example here http://salilkapur.wordpress.com/2013/03/08/communicating-with-arduino-using-c/

**Comment by shamor** [comment]
So far we can write to a file and read from a file on the c side of code. We still need to receive the coordinates on the robot side and write back a response for when it is finished.

**Comment by jcoady9** [comment]
isn't this issue the same as #31 Receive array of vertices from image processing process?

**Comment by sbonner1** [comment]
In response to Josh's comment, I flipped the issues by mistake. Receiving the coordinates is the job for Sam and I, and the sending of the coordinates is for Josh.

**Comment by shamor** [comment]
coordinates are being sent and received properly.
