### ISSUE TITLE
Receive array of vertices from image processing process

### ISSUE THREAD

**Issue by sbonner1** [sbonner1/Senior-Design-I#31]
Sam and I will assist Josh on the array of vertices by trying to figure out from our end the easiest way for the board to receive the information and pass it to the Arduino IDE.

**Comment by jcoady9** [comment]
isn't this issue the same as #30  Send required vertices to Arduino?

**Comment by sbonner1** [comment]
Sam: see if this helps you

 http://playground.arduino.cc/Interfacing/Java

**Comment by sbonner1** [comment]
and this: http://www.varesano.net/blog/fabio/serial-communication-arduino-and-processing-simple-examples-and-arduino-based-gamepad-int

**Comment by shamor** [comment]
Can receive coordinates, however, Arduino doesn't allow them to be parsed correctly.

**Comment by shamor** [comment]
Arduino now parses them correct, it just sucks at sending a response.
