### ISSUE TITLE
figure out way to move motors to draw straight line with robot

### ISSUE THREAD

**Issue by jcoady9** [sbonner1/Senior-Design-I#70]

**Comment by jcoady9** [comment]
somebody should consult Dr. Martin about this issue.

**Comment by sbonner1** [comment]
http://www.openprocessing.org/sketch/553

this is the basic inverse kinematics code

**Comment by sbonner1** [comment]
https://github.com/nkint/TwoServoArm/blob/master/TwoServoArm_PROCESSING/TwoServoArm_PROCESSING.pde

this is the adaptation for a robot with two arms

**Comment by shamor** [comment]
Inverse Kinematics article here : http://freespace.virgin.net/hugo.elias/models/m_ik2.htm

**Comment by shamor** [comment]
Another good article: http://www.learnaboutrobots.com/inverseKinematics.htm

**Comment by shamor** [comment]
A little bit of math translated from the article above: 

int IK(long Xhip, long Yhip, long Xfoot, long Yfoot){//hip and foot refer to the length of the robot segments

 float B;                                    //B: length of imaginary line
 float q1;                                   //q1: angle between X-axis and imaginary line
 float q2;                                   //q2: interior angle between imaginary line and link l1
 float Q1;                                   //Q1: angle between x-axis and "l1"
 float Q2;                                   //Q2: angle between "l1" and "l2"
 long l1 = 124;                              //l1: length of the upper leg in mm
 long l2 = 175;                            //l2: length of the lower leg in mm
 long Xpos;                                  //Xpos: relative X-position out of Xhip and Xfoot where the leg should move to
 long Ypos;                                  //Ypos: relative Y-position out of Yhip and Yfoot where the leg should move to      

 Xpos = abs(Xhip-Xfoot);                                 //relative distance of Xhip and Xfoot
 Ypos = abs(Yhip-Yfoot);                                 //relative distance of Yhip and Yfoot

  B = sqrt(Xpos_Xpos + Ypos_Ypos);                        //the Pythagorean theorem
 q1 = atan2(Ypos,Xpos);
 q2 = acos((l1_l1 - l2_l2 + B_B)/(2_l1_B));              //the law of cosines  
 Q1 = degrees(q2) - degrees(q1) + 90;  
 Q2 = degrees(acos((l1_l1 + l2_l2 - B_B)/(2_l1_l2)));    //the law of cosines  
}found here: http://forum.arduino.cc/index.php?topic=40114.0

**Comment by jcoady9** [comment]
Slightly different code:
void moveArm ( float x, float y) {//position which we are moving to

```
// calculate required servo angles using inverse kinematics 
Serial.println("Calculate servo angles:");

// Work out the length of an imaginery line from the arms shoulder to the x,y position and call it B
// using pythagoras theorem - length of b squared = x sqared + y squared
float B = sqrt ( ( x * x ) + ( y * y ) );
Serial.print("  B = ");     Serial.println( B );

// Calculate the angle of the imaginary line from the x axis and call it QA
float QA = atan2 ( y , x ); 
Serial.print("  QA = ");     Serial.println( QA );

// Calculate the angle from the imaginary line to the humerus (using cosine rule) and call it QB
float B_sq = B * B;    // B squared
float tvala = hum_sq - uln_sq + B_sq ;
float tvalb = 2.0 * humerus * B;
float QB = acos ( tvala / tvalb ); 
Serial.print("  QB = ");     Serial.println( QB );

// Calculate angle of shoulder servo by ading the two calculated angles together
float angleS = QA + QB;
Serial.print("  angleS = ");     Serial.println( angleS );

// Calculate angle of elbow servo
// this is done using the cosine rule 
tvala = hum_sq + uln_sq - B_sq ;
tvalb = 2.0 * humerus * ulna;
float angleE = acos ( tvala / tvalb ); 
Serial.print("  angleE = ");     Serial.println( angleE );


// convert angles from radians to degrees
angleE = angleE * RAD_TO_DEG;
angleS = angleS * RAD_TO_DEG;


Serial.print("moving arm to x=");  Serial.print(x);  Serial.print(" Y=");  Serial.println(y);
Serial.print("  angleS in degrees = ");     Serial.println( angleS );
Serial.print("  angleE in degrees = ");     Serial.println( angleE );
moveServos(angleS,angleE);    // move the servos
```

}

**Comment by jcoady9** [comment]
![image](https://cloud.githubusercontent.com/assets/6423746/5333843/4038d78a-7e52-11e4-92b0-8caff59443dd.png)

**Comment by jcoady9** [comment]
![graph](https://cloud.githubusercontent.com/assets/6423746/5370716/3310bde4-7ff5-11e4-9aa0-c0635538ffaa.gif)
