### ISSUE TITLE
Process image for drawing

### ISSUE THREAD

**Issue by shamor** [sbonner1/Senior-Design-I#8]
Includes edge recognition and conversion to format which the robot can draw.

**Comment by shamor** [comment]
This is being done using line detection (possibly aided by corner detection) to find vertices in which the robot can draw between. Once we get the vertices, we can build a graph and process the vertices in groups. Then each set of vertices can be passed to the arm for drawing.

**Comment by jcoady9** [comment]
general image processing has been accomplished, fine tuning the detection of different lines and features can be dealt as new tracked issues.
